# Generated by Django 3.1.4 on 2021-01-03 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TT', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertt',
            name='description',
            field=models.CharField(max_length=140, null=True),
        ),
        migrations.AlterField(
            model_name='usertt',
            name='profile_pic',
            field=models.ImageField(blank=True, upload_to='profile_pics'),
        ),
    ]
