# Generated by Django 3.1.4 on 2021-01-03 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TT', '0002_auto_20210103_1441'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_pic',
            field=models.ImageField(blank=True, upload_to='post_pics'),
        ),
    ]
