# Generated by Django 3.1.4 on 2021-01-11 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TT', '0003_post_post_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
