# Generated by Django 3.1.4 on 2021-01-13 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TT', '0006_auto_20210113_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_pic',
            field=models.ImageField(blank=True, null=True, upload_to='post_pics'),
        ),
    ]
